[project]
name = "standards-explorer-mcp"
version = "0.1.0"
description = "A Model Context Protocol (MCP) implementation for exploring standards from the Bridge2AI Standards Explorer."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.12.5",
    "httpx>=0.27.0",
]
